name: your_app_name  # Замените на имя вашего приложения
description: A Flutter application to manage product expiration dates.

environment:
  sdk: ">=2.12.0 <3.0.0"  # Убедитесь, что версия SDK соответствует вашей версии Flutter

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.9.1  # Пакет для уведомлений
  google_ml_kit: ^0.18.1                # Пакет для работы с машинным обучением
  http: ^1.2.2                           # Пакет для HTTP-запросов
  image_picker: ^1.1.2                   # Пакет для выбора изображений
  file_picker: ^5.0.0                    # Пакет для выбора файлов (если понадобится)
  path_provider: ^2.0.11                  # Пакет для работы с путями файловой системы
  provider: ^6.0.5                        # Пакет для управления состоянием
  intl: ^0.18.0                           # Пакет для работы с датами и временем

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true  # Включает поддержку Material Design
