name: my_flutter_app #1
description: A new Flutter project.

# Параметры SDK
environment:
  sdk: ">=2.17.0 <3.0.0"

# Зависимости проекта
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.9
  google_ml_kit: ^0.7.3
  http: ^1.2.2
  flutter_local_notifications: ^9.9.1
  flutter_local_notifications_linux: ^0.5.1
  flutter_local_notifications_platform_interface: ^5.0.0
  path: ^1.9.0
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  leak_tracker_testing: ^3.0.1
  timezone: ^0.8.0
  # Добавьте другие зависимости, если они используются

# Зависимости для тестирования
dev_dependencies:
  flutter_test:
    sdk: flutter

# Укажите используемую версию Flutter
flutter:
  uses-material-design: true
